name: bci-arco-gp
channels:
  - gpytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter==1.1.1
  - matplotlib==3.10.0
  - networkx==3.4.2
  - numpy==1.26.4
  - pip==25.0
  - python==3.12.8
  - scipy==1.11.4
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - causal-learn==0.1.4.0
      - gadjid==0.1.0
      - gcastle==1.0.3
      - gpytorch==1.14
      - lingam==1.9.1
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - sumu==0.1.2
      - torch==2.6.0+cpu
      - torchaudio==2.6.0+cpu
      - torchvision==0.21.0+cpu